/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedBriefsRouteImport } from './routes/_authenticated/briefs'
import { Route as AuthenticatedBriefsIndexRouteImport } from './routes/_authenticated/briefs.index'
import { Route as AuthenticatedBriefsIdRouteImport } from './routes/_authenticated/briefs.$id'
import { Route as AuthenticatedBriefsIdIndexRouteImport } from './routes/_authenticated/briefs.$id.index'
import { Route as AuthenticatedBriefsIdCandidatesRouteImport } from './routes/_authenticated/briefs.$id.candidates'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefsRoute = AuthenticatedBriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefsIndexRoute =
  AuthenticatedBriefsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBriefsRoute,
  } as any)
const AuthenticatedBriefsIdRoute = AuthenticatedBriefsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBriefsRoute,
} as any)
const AuthenticatedBriefsIdIndexRoute =
  AuthenticatedBriefsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBriefsIdRoute,
  } as any)
const AuthenticatedBriefsIdCandidatesRoute =
  AuthenticatedBriefsIdCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AuthenticatedBriefsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/briefs': typeof AuthenticatedBriefsRouteWithChildren
  '/new': typeof AuthenticatedNewRoute
  '/briefs/$id': typeof AuthenticatedBriefsIdRouteWithChildren
  '/briefs/': typeof AuthenticatedBriefsIndexRoute
  '/briefs/$id/candidates': typeof AuthenticatedBriefsIdCandidatesRoute
  '/briefs/$id/': typeof AuthenticatedBriefsIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/new': typeof AuthenticatedNewRoute
  '/': typeof AuthenticatedIndexRoute
  '/briefs': typeof AuthenticatedBriefsIndexRoute
  '/briefs/$id/candidates': typeof AuthenticatedBriefsIdCandidatesRoute
  '/briefs/$id': typeof AuthenticatedBriefsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/briefs': typeof AuthenticatedBriefsRouteWithChildren
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/briefs/$id': typeof AuthenticatedBriefsIdRouteWithChildren
  '/_authenticated/briefs/': typeof AuthenticatedBriefsIndexRoute
  '/_authenticated/briefs/$id/candidates': typeof AuthenticatedBriefsIdCandidatesRoute
  '/_authenticated/briefs/$id/': typeof AuthenticatedBriefsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/briefs'
    | '/new'
    | '/briefs/$id'
    | '/briefs/'
    | '/briefs/$id/candidates'
    | '/briefs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/new'
    | '/'
    | '/briefs'
    | '/briefs/$id/candidates'
    | '/briefs/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/briefs'
    | '/_authenticated/new'
    | '/_authenticated/'
    | '/_authenticated/briefs/$id'
    | '/_authenticated/briefs/'
    | '/_authenticated/briefs/$id/candidates'
    | '/_authenticated/briefs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefs': {
      id: '/_authenticated/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof AuthenticatedBriefsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefs/': {
      id: '/_authenticated/briefs/'
      path: '/'
      fullPath: '/briefs/'
      preLoaderRoute: typeof AuthenticatedBriefsIndexRouteImport
      parentRoute: typeof AuthenticatedBriefsRoute
    }
    '/_authenticated/briefs/$id': {
      id: '/_authenticated/briefs/$id'
      path: '/$id'
      fullPath: '/briefs/$id'
      preLoaderRoute: typeof AuthenticatedBriefsIdRouteImport
      parentRoute: typeof AuthenticatedBriefsRoute
    }
    '/_authenticated/briefs/$id/': {
      id: '/_authenticated/briefs/$id/'
      path: '/'
      fullPath: '/briefs/$id/'
      preLoaderRoute: typeof AuthenticatedBriefsIdIndexRouteImport
      parentRoute: typeof AuthenticatedBriefsIdRoute
    }
    '/_authenticated/briefs/$id/candidates': {
      id: '/_authenticated/briefs/$id/candidates'
      path: '/candidates'
      fullPath: '/briefs/$id/candidates'
      preLoaderRoute: typeof AuthenticatedBriefsIdCandidatesRouteImport
      parentRoute: typeof AuthenticatedBriefsIdRoute
    }
  }
}

interface AuthenticatedBriefsIdRouteChildren {
  AuthenticatedBriefsIdCandidatesRoute: typeof AuthenticatedBriefsIdCandidatesRoute
  AuthenticatedBriefsIdIndexRoute: typeof AuthenticatedBriefsIdIndexRoute
}

const AuthenticatedBriefsIdRouteChildren: AuthenticatedBriefsIdRouteChildren = {
  AuthenticatedBriefsIdCandidatesRoute: AuthenticatedBriefsIdCandidatesRoute,
  AuthenticatedBriefsIdIndexRoute: AuthenticatedBriefsIdIndexRoute,
}

const AuthenticatedBriefsIdRouteWithChildren =
  AuthenticatedBriefsIdRoute._addFileChildren(
    AuthenticatedBriefsIdRouteChildren,
  )

interface AuthenticatedBriefsRouteChildren {
  AuthenticatedBriefsIdRoute: typeof AuthenticatedBriefsIdRouteWithChildren
  AuthenticatedBriefsIndexRoute: typeof AuthenticatedBriefsIndexRoute
}

const AuthenticatedBriefsRouteChildren: AuthenticatedBriefsRouteChildren = {
  AuthenticatedBriefsIdRoute: AuthenticatedBriefsIdRouteWithChildren,
  AuthenticatedBriefsIndexRoute: AuthenticatedBriefsIndexRoute,
}

const AuthenticatedBriefsRouteWithChildren =
  AuthenticatedBriefsRoute._addFileChildren(AuthenticatedBriefsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBriefsRoute: typeof AuthenticatedBriefsRouteWithChildren
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBriefsRoute: AuthenticatedBriefsRouteWithChildren,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
